services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    ports:
      - "5000:5000"

volumes:
  mysql_data: